[package]
name = "itretail_automation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
clap = "4.2.7"
home = "0.5.5"
regex = "1.8.1"
reqwest = { version = "0.11.17", features = ["json", "blocking"] }
rust_xlsxwriter = "0.38.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_derive = "1.0.160"
serde_json = "1.0.96"
